# Generated by Django 2.2.10 on 2020-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_key_word_1',
            field=models.CharField(default='Artificial Intelligence', max_length=75),
        ),
        migrations.AddField(
            model_name='post',
            name='post_key_word_2',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='post',
            name='post_key_word_3',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
