# Generated by Django 2.2.10 on 2020-07-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200, unique=True)),
                ('project_slug', models.SlugField(max_length=200, unique=True)),
                ('project_collaborator_1', models.CharField(blank=True, max_length=100)),
                ('project_collaborator_2', models.CharField(blank=True, max_length=100)),
                ('project_abstract', models.TextField()),
                ('project_description', models.TextField()),
                ('project_status', models.IntegerField(choices=[(0, 'Secret'), (1, 'Open'), (2, 'Closed')], default=0)),
                ('project_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_closed_on', models.DateTimeField(blank=True)),
                ('project_key_word_1', models.CharField(max_length=75)),
                ('project_key_word_2', models.CharField(blank=True, max_length=75)),
                ('project_key_word_3', models.CharField(blank=True, max_length=75)),
                ('project_key_word_4', models.CharField(blank=True, max_length=75)),
                ('project_key_word_5', models.CharField(blank=True, max_length=75)),
                ('project_description_link_1', models.CharField(blank=True, max_length=150)),
                ('project_description_link_2', models.CharField(blank=True, max_length=150)),
                ('project_description_link_3', models.CharField(blank=True, max_length=150)),
                ('project_description_link_4', models.CharField(blank=True, max_length=150)),
                ('project_description_link_5', models.CharField(blank=True, max_length=150)),
                ('project_link_1', models.CharField(blank=True, max_length=150)),
                ('project_link_2', models.CharField(blank=True, max_length=150)),
                ('project_link_3', models.CharField(blank=True, max_length=150)),
                ('project_link_4', models.CharField(blank=True, max_length=150)),
                ('project_link_5', models.CharField(blank=True, max_length=150)),
                ('project_miniature', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_image_1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_image_2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_image_3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_image_4', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_image_5', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_created_on'],
            },
        ),
    ]
