# Generated by Django 2.2.10 on 2020-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(default=999999, primary_key=True, serialize=False),
        ),
    ]
