# Generated by Django 2.2.10 on 2020-07-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200715_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
