# Generated by Django 2.2.10 on 2020-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200628_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_link_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='description_link_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='description_link_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='description_link_4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='description_link_5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
