# Generated by Django 2.2.10 on 2020-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200628_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
