# Generated by Django 2.2.10 on 2020-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200709_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.AutoField(default=999999, primary_key=True, serialize=False),
        ),
    ]
